name: example
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  crdt: ^5.1.3
  drift: ^2.21.0
  drift_flutter: ^0.2.1
  flutter:
    sdk: flutter

  pocketbase: ^0.18.1
  pocketbase_crdt:
    path: ..
  signals: ^5.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  test: ^1.25.7
  build_web_compilers: ^4.0.11
  build_runner: ^2.4.13
  build: ^2.4.1

flutter:

  uses-material-design: true

