name: pocketbase_crdt
description: CRDT for PocketBase
version: 0.0.1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  crdt: ^5.1.2
  crdt_sync: ^1.0.9
  drift: ^2.21.0
  pocketbase: ^0.18.1
  shelf_cors_headers: ^0.1.5
  shelf_router: ^1.1.4
  shelf_web_socket: ^2.0.0
  version: ^3.0.2
  web_socket_channel: ^2.4.0

dev_dependencies:
  flutter_lints: ^3.0.0
  drift_dev: ^2.21.0
  build_runner: ^2.4.11
