name: pocketbase_crdt
description: CRDT for PocketBase
version: 0.0.1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  crdt: ^5.1.2
  drift: ^2.21.0
  intl: ^0.19.0
  path_provider: ^2.1.5
  pocketbase: ^0.18.1

dev_dependencies:
  flutter_lints: ^3.0.0
  drift_dev: ^2.21.0
  build_runner: ^2.4.11
  test: ^1.25.8
